# 02 — Preparação dos Dados

## Pergunta de investigação

> **Conseguimos transformar esses dados num dataset utilizável?**

Neste notebook será realizada a preparação dos dados recolhidos.

### Objetivos

- Limpar os dados;
- Corrigir ou tratar valores em falta;
- Normalizar formatos;
- Organizar as séries temporais;
- Criar o dataset final para análise e modelação.

In [18]:
import pandas as pd
from pathlib import Path

DATA_PROCESSED = Path("../data/processed")

materials_index_path = DATA_PROCESSED / "materials_index.csv"

materials_history = pd.read_csv(
    materials_index_path,
    encoding="utf-8"
)

materials_history.head()

    ano codigo material  mes  indice                ficheiro
0  2015    M01   Britas  JAN   104.4  cife2015_MATERIAIS.xls
1  2015    M01   Britas  FEV   104.7  cife2015_MATERIAIS.xls
2  2015    M01   Britas  MAR   105.0  cife2015_MATERIAIS.xls
3  2015    M01   Britas  ABR   104.8  cife2015_MATERIAIS.xls
4  2015    M01   Britas  MAI   104.5  cife2015_MATERIAIS.xls

In [19]:
print("Dimensão:", materials_history.shape)
print("\nColunas:")
print(materials_history.columns.tolist())

print("\nTipos:")
print(materials_history.dtypes)

Dimensão: (7644, 6)

Colunas:
['ano', 'codigo', 'material', 'mes', 'indice', 'ficheiro']

Tipos:
ano           int64
codigo          str
material        str
mes             str
indice      float64
ficheiro        str
dtype: object

In [20]:
materials_history.isna().sum()

ano           0
codigo        0
material      0
mes           0
indice      290
ficheiro      0
dtype: int64

In [21]:
duplicados = materials_history.duplicated(
    subset=["ano", "codigo", "mes"]
).sum()

print(f"Registos duplicados: {duplicados}")

Registos duplicados: 0

In [22]:
meses = {
    "JAN": 1,
    "FEV": 2,
    "MAR": 3,
    "ABR": 4,
    "MAI": 5,
    "JUN": 6,
    "JUL": 7,
    "AGO": 8,
    "SET": 9,
    "OUT": 10,
    "NOV": 11,
    "DEZ": 12
}

materials_history["mes_num"] = (
    materials_history["mes"]
    .str.upper()
    .str.strip()
    .map(meses)
)

In [23]:
print(
    materials_history[
        ["ano", "mes", "mes_num"]
    ].drop_duplicates().head(15)
)

      ano  mes  mes_num
0    2015  JAN        1
1    2015  FEV        2
2    2015  MAR        3
3    2015  ABR        4
4    2015  MAI        5
5    2015  JUN        6
6    2015  JUL        7
7    2015  AGO        8
8    2015  SET        9
9    2015  OUT       10
10   2015  NOV       11
11   2015  DEZ       12
588  2016  JAN        1
589  2016  FEV        2
590  2016  MAR        3

In [24]:
materials_history["data"] = pd.to_datetime(
    dict(
        year=materials_history["ano"],
        month=materials_history["mes_num"],
        day=1
    )
)

materials_history.head()

,ano,codigo,material,mes,indice,ficheiro,mes_num,data
0,2015,M01,Britas,JAN,104.4,cife2015_MATERIAIS.xls,1,2015-01-01
1,2015,M01,Britas,FEV,104.7,cife2015_MATERIAIS.xls,2,2015-02-01
2,2015,M01,Britas,MAR,105.0,cife2015_MATERIAIS.xls,3,2015-03-01
3,2015,M01,Britas,ABR,104.8,cife2015_MATERIAIS.xls,4,2015-04-01
4,2015,M01,Britas,MAI,104.5,cife2015_MATERIAIS.xls,5,2015-05-01

In [25]:
coverage = (
    materials_history
    .groupby(["ano", "codigo"])
    .size()
    .unstack(fill_value=0)
)

coverage.head()

codigo,M01,M02,M03,M04,M05,M06,M07,M08,M09,M10,...,M51,M52,M53,M54,M55,M56,M57,M58,M59,M60
ano,,,,,,,,,,,,,,,,,,,,,
2015,12,12,12,12,12,12,12,12,12,12,...,12,0,0,0,0,0,0,0,0,0
2016,12,12,12,12,12,12,12,12,12,12,...,12,0,0,0,0,0,0,0,0,0
2017,12,12,12,12,12,12,12,12,12,12,...,12,0,0,0,0,0,0,0,0,0
2018,12,12,12,12,12,12,12,12,12,12,...,12,0,0,0,0,0,0,0,0,0
2019,12,12,12,12,12,12,12,12,12,12,...,12,0,0,0,0,0,0,0,0,0

In [26]:
incompletos = (
    materials_history
    .groupby(["ano", "codigo"])
    .size()
    .reset_index(name="meses")
)

incompletos[incompletos["meses"] != 12].head(20)

Empty DataFrame
Columns: [ano, codigo, meses]
Index: []

In [27]:
materials_prepared_path = (
    DATA_PROCESSED / "materials_history.csv"
)

materials_history.to_csv(
    materials_prepared_path,
    index=False,
    encoding="utf-8"
)

print(f"Dataset preparado guardado em:")
print(materials_prepared_path)

Dataset preparado guardado em:
..\data\processed\materials_history.csv

In [28]:
material_coverage = (
    materials_history
    .groupby(["codigo", "material"])
    .agg(
        primeiro_ano=("ano", "min"),
        ultimo_ano=("ano", "max"),
        anos=("ano", "nunique"),
        registos=("indice", "count")
    )
    .reset_index()
    .sort_values("codigo")
)

material_coverage

,codigo,material,primeiro_ano,ultimo_ano,anos,registos
0,M01,Britas,2015,2026,12,139
1,M02,Areias,2015,2026,12,139
2,M03,Inertes,2015,2026,12,139
3,M04,Ladrilhos de calcário e granito,2015,2026,12,139
4,M05,Cantarias de calcário e granito,2015,2026,12,139
5,M06,Ladr. e cant. de calcário e granito,2015,2026,12,139
6,M07,Telhas cerâmicas,2015,2026,12,139
7,M08,Tijolos cerâmicos,2015,2026,12,139
8,M09,Produtos Cerâmicos Vermelhos,2015,2026,12,139
9,M10,Azulejos e Mosaicos,2015,2026,12,139
10,M12,Aço em Varão e Perfilados,2015,2026,12,139
11,M13,Chapa de Aço Macio,2015,2026,12,139
12,M14,Rede electrossoldada,2015,2026,12,139
13,M15,Chapa de aço galvanizada,2015,2026,12,139
14,M16,Fio de Cobre Nu,2015,2026,12,139
15,M17,Fio de cobre revestido,2015,2026,12,139
16,M18,Betumes a Granel,2015,2026,12,139
17,M19,Betumes em Tambores,2015,2026,12,139
18,M20,Cimento em saco,2015,2026,12,139
19,M21,Explosivos,2015,2026,12,139
20,M22,Gasóleo,2015,2026,12,139
21,M23,Vidro,2015,2026,12,139
22,M24,Madeiras de Pinho,2015,2026,12,139
23,M25,Madeiras Especiais ou Exóticas,2015,2026,12,139
24,M26,Derivados de madeira,2015,2026,12,139
25,M27,Aglomerado negro de cortiça,2015,2026,12,139
26,M28,Ladrilho de cortiça,2015,2026,12,139
27,M29,Tintas para construção civil,2015,2026,12,139
28,M30,Tintas para estradas,2015,2026,12,139
29,M31,Membrana betuminosa,2015,2026,12,139
30,M32,Tubo de PVC,2015,2026,12,139
31,M33,Tubo de PVC p/ instalações elétricas,2015,2026,12,139
32,M34,Blocos de betão normal,2015,2026,12,139
33,M35,Manilhas de betão,2015,2026,12,139
34,M36,Tubagem de fibrocimento,2015,2026,12,139
35,M37,Chapa de fibrocimento (1),2015,2026,12,139
36,M39,Caixilharias em alumínio anodizado,2015,2026,12,139
37,M40,Caixilharias em alumínio termolacado,2015,2026,12,139
38,M41,Pavimentos aligeirados de vigotas pré-esforçad...,2015,2026,12,139
39,M42,Tubagem de aço e aparelhos para canalizações,2015,2026,12,139
40,M43,Aço para betão armado,2015,2026,12,139
41,M44,Aço para betão pré-esforçado,2015,2026,12,139
42,M45,Perfilados pesados e ligeiros,2015,2026,12,139
43,M46,Produtos para instalações elétricas,2015,2026,12,139
44,M47,Produtos pré-fabricados de betão,2015,2026,12,139
45,M48,Produtos para ajardinamentos,2015,2026,12,139
46,M49,Geotêxteis,2015,2026,12,139
47,M50,Tubos e Acessórios de Ferro Fundido e Aço,2015,2026,12,139
48,M51,Tintas para Construções Metálicas,2015,2026,12,139
49,M52,Redes e equipamentos de média e alta tensão,2020,2026,7,79
50,M53,Tubagem e acessórios para redes prediais de di...,2020,2026,7,79
51,M54,Produtos com base em ligantes minerais pré-dos...,2020,2026,7,79
52,M55,Chapas e painéis para revestimento de coberturas,2020,2026,7,79
53,M56,Sistemas compósitos de isolamento térmico pelo...,2020,2026,7,79
54,M57,Isolamentos térmicos e acústicos,2020,2026,7,79
55,M58,Janelas e portas de alumínio e PVC,2022,2026,5,55
56,M59,"Tubagens de abastecimento de água em ""alta"" (1)",2026,2026,1,7
57,M60,Janelas e portas de PVC,2026,2026,1,7

In [29]:
material_start = (
    materials_history
    .groupby("codigo")
    .agg(
        primeiro_ano=("ano", "min"),
        material=("material", "first")
    )
    .reset_index()
)

material_start

   codigo  primeiro_ano                                           material
0     M01          2015                                             Britas
1     M02          2015                                             Areias
2     M03          2015                                            Inertes
3     M04          2015                    Ladrilhos de calcário e granito
4     M05          2015                    Cantarias de calcário e granito
5     M06          2015                Ladr. e cant. de calcário e granito
6     M07          2015                                   Telhas cerâmicas
7     M08          2015                                  Tijolos cerâmicos
8     M09          2015                       Produtos Cerâmicos Vermelhos
9     M10          2015                                Azulejos e Mosaicos
10    M12          2015                          Aço em Varão e Perfilados
11    M13          2015                                 Chapa de Aço Macio
12    M14          2015                               Rede electrossoldada
13    M15          2015                           Chapa de aço galvanizada
14    M16          2015                                    Fio de Cobre Nu
15    M17          2015                             Fio de cobre revestido
16    M18          2015                                   Betumes a Granel
17    M19          2015                                Betumes em Tambores
18    M20          2015                                    Cimento em saco
19    M21          2015                                         Explosivos
20    M22          2015                                            Gasóleo
21    M23          2015                                              Vidro
22    M24          2015                                  Madeiras de Pinho
23    M25          2015                     Madeiras Especiais ou Exóticas
24    M26          2015                               Derivados de madeira
25    M27          2015                        Aglomerado negro de cortiça
26    M28          2015                                Ladrilho de cortiça
27    M29          2015                       Tintas para construção civil
28    M30          2015                               Tintas para estradas
29    M31          2015                                Membrana betuminosa
30    M32          2015                                        Tubo de PVC
31    M33          2015               Tubo de PVC p/ instalações elétricas
32    M34          2015                             Blocos de betão normal
33    M35          2015                                  Manilhas de betão
34    M36          2015                            Tubagem de fibrocimento
35    M37          2015                          Chapa de fibrocimento (1)
36    M39          2015                 Caixilharias em alumínio anodizado
37    M40          2015               Caixilharias em alumínio termolacado
38    M41          2015  Pavimentos aligeirados de vigotas pré-esforçad...
39    M42          2015       Tubagem de aço e aparelhos para canalizações
40    M43          2015                              Aço para betão armado
41    M44          2015                       Aço para betão pré-esforçado
42    M45          2015                      Perfilados pesados e ligeiros
43    M46          2015                Produtos para instalações elétricas
44    M47          2015                   Produtos pré-fabricados de betão
45    M48          2015                       Produtos para ajardinamentos
46    M49          2015                                         Geotêxteis
47    M50          2015          Tubos e Acessórios de Ferro Fundido e Aço
48    M51          2015                  Tintas para Construções Metálicas
49    M52          2020        Redes e equipamentos de média e alta tensão
50    M53          2020  Tubagem e acessórios para redes prediais de di...
51    M54          2020  Produtos com base em ligantes minerais pré-dos...
52    M55          2020   Chapas e painéis para revestimento de coberturas
53    M56          2020  Sistemas compósitos de isolamento térmico pelo...
54    M57          2020                   Isolamentos térmicos e acústicos
55    M58          2022                 Janelas e portas de alumínio e PVC
56    M59          2026    Tubagens de abastecimento de água em "alta" (1)
57    M60          2026                            Janelas e portas de PVC

In [30]:
import json

materials_catalog_path = (
    DATA_PROCESSED / "materials_catalog.json"
)

with open(
    materials_catalog_path,
    "r",
    encoding="utf-8"
) as f:
    materials_catalog = pd.DataFrame(json.load(f))

print(f"Materiais no catálogo: {len(materials_catalog)}")
materials_catalog.head()

Materiais no catálogo: 58

  codigo                        descricao
0    M01                           Britas
1    M02                           Areias
2    M03                          Inertes
3    M04  Ladrilhos de calcário e granito
4    M05  Cantarias de calcário e granito

In [31]:
catalog_codes = set(materials_catalog["codigo"])

history_codes = set(materials_history["codigo"])

print("No catálogo mas sem histórico:")
print(sorted(catalog_codes - history_codes))

print("\nNo histórico mas não no catálogo:")
print(sorted(history_codes - catalog_codes))

No catálogo mas sem histórico:
[]

No histórico mas não no catálogo:
[]

In [32]:
materials_catalog

   codigo                                          descricao
0     M01                                             Britas
1     M02                                             Areias
2     M03                                            Inertes
3     M04                    Ladrilhos de calcário e granito
4     M05                    Cantarias de calcário e granito
5     M06                Ladr. e cant. de calcário e granito
6     M07                                   Telhas cerâmicas
7     M08                                  Tijolos cerâmicos
8     M09                       Produtos Cerâmicos Vermelhos
9     M10                                Azulejos e Mosaicos
10    M12                          Aço em Varão e Perfilados
11    M13                                 Chapa de Aço Macio
12    M14                               Rede electrossoldada
13    M15                           Chapa de aço galvanizada
14    M16                                    Fio de Cobre Nu
15    M17                             Fio de cobre revestido
16    M18                                   Betumes a Granel
17    M19                                Betumes em Tambores
18    M20                                    Cimento em saco
19    M21                                         Explosivos
20    M22                                            Gasóleo
21    M23                                              Vidro
22    M24                                  Madeiras de Pinho
23    M25                     Madeiras Especiais ou Exóticas
24    M26                               Derivados de madeira
25    M27                        Aglomerado negro de cortiça
26    M28                                Ladrilho de cortiça
27    M29                       Tintas para construção civil
28    M30                               Tintas para estradas
29    M31                                Membrana betuminosa
30    M32                                        Tubo de PVC
31    M33               Tubo de PVC p/ instalações elétricas
32    M34                             Blocos de betão normal
33    M35                                  Manilhas de betão
34    M36                            Tubagem de fibrocimento
35    M37                          Chapa de fibrocimento (1)
36    M39                 Caixilharias em alumínio anodizado
37    M40               Caixilharias em alumínio termolacado
38    M41  Pavimentos aligeirados de vigotas pré-esforçad...
39    M42       Tubagem de aço e aparelhos para canalizações
40    M43                              Aço para betão armado
41    M44                       Aço para betão pré-esforçado
42    M45                      Perfilados pesados e ligeiros
43    M46                Produtos para instalações elétricas
44    M47                   Produtos pré-fabricados de betão
45    M48                       Produtos para ajardinamentos
46    M49                                         Geotêxteis
47    M50          Tubos e Acessórios de Ferro Fundido e Aço
48    M51                  Tintas para Construções Metálicas
49    M52        Redes e equipamentos de média e alta tensão
50    M53  Tubagem e acessórios para redes prediais de di...
51    M54  Produtos com base em ligantes minerais pré-dos...
52    M55   Chapas e painéis para revestimento de coberturas
53    M56  Sistemas compósitos de isolamento térmico pelo...
54    M57                   Isolamentos térmicos e acústicos
55    M58                 Janelas e portas de alumínio e PVC
56    M59    Tubagens de abastecimento de água em "alta" (1)
57    M60                            Janelas e portas de PVC